# Generated by Django 3.2.7 on 2022-06-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=500)),
                ('categoria', models.ManyToManyField(to='proyectos.Categoria')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.profesor')),
            ],
        ),
    ]
