# Generated by Django 3.2.7 on 2022-08-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enPapelera', models.BooleanField(default='False')),
                ('fechaPapelera', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enPapelera', models.BooleanField(default='False')),
                ('fechaPapelera', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=500)),
                ('area', models.ManyToManyField(to='proyectos.Area')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.profesor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enPapelera', models.BooleanField(default='False')),
                ('fechaPapelera', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=500)),
                ('general', models.BooleanField(verbose_name=False)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
