# Generated by Django 3.2.7 on 2022-07-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20220628_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enPapelera', models.BooleanField(default='False')),
                ('fechaPapelera', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=500)),
                ('general', models.BooleanField(verbose_name=False)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enPapelera', models.BooleanField(default='False')),
                ('fechaPapelera', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=500)),
                ('objetivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.objetivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
