# Generated by Django 3.2.7 on 2022-07-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_meta_objetivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
