# Generated by Django 3.2.7 on 2022-08-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '__first__'),
        ('cuentas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enPapelera', models.BooleanField(default='False')),
                ('fechaPapelera', models.DateField(blank=True, null=True)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField()),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'En Revisión')], default='En Revisión', max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.estudiante')),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
