# Generated by Django 3.2.7 on 2022-06-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField()),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'En Revisión')], default='En Revisión', max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.estudiante')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
    ]
