# Generated by Django 3.2.7 on 2022-06-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tarea',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea'),
            preserve_default=False,
        ),
    ]
