# Generated by Django 3.2.7 on 2022-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        ('actividades', '0002_actividad_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tarea',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tarea',
            field=models.ManyToManyField(to='tareas.Tarea'),
        ),
    ]
