# Generated by Django 3.2.7 on 2022-06-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        ('actividades', '0003_auto_20220624_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tarea',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea'),
        ),
    ]
