# Generated by Django 3.2.7 on 2022-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_actividad_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='enPapelera',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fechaPapelera',
            field=models.DateField(null=True),
        ),
    ]
