# Generated by Django 3.2.7 on 2022-06-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20220628_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaPapelera',
            field=models.DateField(blank=True, null=True),
        ),
    ]
