# Generated by Django 3.2.7 on 2022-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='enPapelera',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaPapelera',
            field=models.DateField(blank=True, null=True),
        ),
    ]
