# Generated by Django 3.2.7 on 2022-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20220626_2129'),
        ('tareas', '0003_auto_20220628_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estudiante',
            field=models.ManyToManyField(to='cuentas.Estudiante'),
        ),
    ]
