# Generated by Django 3.2.7 on 2022-07-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20220713_2200'),
        ('tareas', '0004_auto_20220711_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionesEnviadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.estudiante')),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea')),
            ],
        ),
    ]
