# Generated by Django 3.2.7 on 2022-07-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_meta_objetivo'),
        ('tareas', '0005_asignacionesenviadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='tarea',
            name='meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.meta'),
        ),
    ]
