# Generated by Django 3.2.7 on 2022-07-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_auto_20220720_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='meta',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tareaSuperior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea'),
        ),
    ]
