# Generated by Django 3.2.7 on 2022-07-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_meta_objetivo'),
        ('tareas', '0007_auto_20220730_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.objetivo'),
        ),
    ]
