# Generated by Django 4.1.2 on 2022-10-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estudiante", old_name="fechaInicioTCU", new_name="fecha_inicio",
        ),
    ]
