# Generated by Django 4.1.2 on 2022-10-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_rename_fechainiciotcu_estudiante_fecha_inicio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estudiante", old_name="fechaFinTCU", new_name="fecha_final",
        ),
    ]
