# Generated by Django 3.2.7 on 2022-06-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_carrera_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.carrera'),
        ),
    ]
