# Generated by Django 3.2.7 on 2022-07-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20220626_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
