# Generated by Django 3.2.7 on 2022-07-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20220712_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='fechaFinal',
            new_name='fechaFinTCU',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='fechaInicio',
            new_name='fechaInicioTCU',
        ),
    ]
