# Generated by Django 3.2.7 on 2022-07-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='otro',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
