# Generated by Django 3.2.7 on 2022-07-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_otro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
