# Generated by Django 4.1.2 on 2022-10-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("F", "Finalización"),
                    ("P", "Prórroga"),
                    ("A", "Pasantía"),
                    ("O", "Otros"),
                ],
                max_length=1,
            ),
        ),
    ]
