# Generated by Django 3.2.7 on 2022-07-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20220628_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarchivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
